#pragma once
#define PROJECT_ICON ":/SatExplorer/svg/project1.svg"
#define FOLDER_ICON ":/SatExplorer/svg/folder.svg"
#define IMAGEDATA_ICON ":/SatExplorer/svg/imagedata.svg"
#define APP_ICON ":/SatExplorer/icon/InSARapp.ico"
#define TEMPLATE_FOLDER ":/SatExplorer/svg/toolbox.svg"
#define TEMPLATE_TOOL ":/SatExplorer/svg/tool.svg"
#define EXPORT_ICON ":/SatExplorer/svg/export.svg"
#define CUT_ICON ":/SatExplorer/svg/cut.svg"
#define IMPORT_ICON ":/SatExplorer/svg/import.svg"
#define IMPORT_BATCH_ICON ":/SatExplorer/svg/import_batch.svg"
#define MATCH_ICON ":/SatExplorer/svg/coregistration.svg"
#define IMAGE_VIEWER_ICON ":/SatExplorer/svg/image_viewer.svg"
#define NOTE_ICON ":/SatExplorer/svg/note.svg"
#define LOGGER_ICON ":/SatExplorer/svg/logger.svg"
#define ZOOM_ICON ":/SatExplorer/svg/zoom.svg"
#define HAND_ICON ":/SatExplorer/svg/hand.svg"
#define MARK_ICON ":/SatExplorer/svg/mark.svg"
#define CURSOR_UP_ICON ":/SatExplorer/svg/cursor_up.svg"
#define CURSOR_DOWN_ICON ":/SatExplorer/svg/cursor_down.svg"
#define GCP_ICON ":/SatExplorer/svg/GCPs.svg"
#define DELETE_ICON ":/SatExplorer/svg/delete.svg"
#define BIGICON_BG ":/SatExplorer/BigIcon.PNG"

#define NOT_IN_PROCESS "not_in_process"
#define IN_PROCESS "in_process"
