#pragma once
#define PROJECT_ICON ":/SatExplorer/icon/project1.png"
#define FOLDER_ICON ":/SatExplorer/icon/folder.png"
#define IMAGEDATA_ICON ":/SatExplorer/icon/imagedata.png"
#define APP_ICON ":/SatExplorer/icon/InSARapp.ico"
#define TEMPLATE_FOLDER ":/SatExplorer/icon/toolbox.png"
#define TEMPLATE_TOOL ":/SatExplorer/icon/tool.png"
#define EXPORT_ICON ":/SatExplorer/icon/export.png"
#define CUT_ICON ":/SatExplorer/icon/cut.png"
#define IMPORT_ICON ":/SatExplorer/icon/import.png"
#define MATCH_ICON ":/SatExplorer/icon/coregistration.png"
#define ZOOM_ICON ":/SatExplorer/icon/zoom.png"
#define HAND_ICON ":/SatExplorer/icon/hand.png"
#define MARK_ICON ":/SatExplorer/icon/mark.png"
#define CURSOR_UP_ICON ":/SatExplorer/icon/cursor_up.png"
#define CURSOR_DOWN_ICON ":/SatExplorer/icon/cursor_down.png"
#define GCP_ICON ":/SatExplorer/icon/GCPs.png"
#define DELETE_ICON ":/SatExplorer/icon/delete.png"

#define NOT_IN_PROCESS "not_in_process"
#define IN_PROCESS "in_process"
