#pragma once
#define PROJECT_ICON ":/QtWidgetsApplication3/icon/project1.png"
#define FOLDER_ICON ":/QtWidgetsApplication3/icon/folder.png"
#define IMAGEDATA_ICON ":/QtWidgetsApplication3/icon/imagedata.png"
#define APP_ICON ":/QtWidgetsApplication3/icon/InSARapp.ico"
#define TEMPLATE_FOLDER ":/QtWidgetsApplication3/icon/toolbox.png"
#define TEMPLATE_TOOL ":/QtWidgetsApplication3/icon/tool.png"
#define EXPORT_ICON ":/QtWidgetsApplication3/icon/export.png"
#define CUT_ICON ":/QtWidgetsApplication3/icon/cut.png"
#define IMPORT_ICON ":/QtWidgetsApplication3/icon/import.png"
#define MATCH_ICON ":/QtWidgetsApplication3/icon/coregistration.png"
#define ZOOM_ICON ":/QtWidgetsApplication3/icon/zoom.png"
#define HAND_ICON ":/QtWidgetsApplication3/icon/hand.png"
#define MARK_ICON ":/QtWidgetsApplication3/icon/mark.png"
#define CURSOR_UP_ICON ":/QtWidgetsApplication3/icon/cursor_up.png"
#define CURSOR_DOWN_ICON ":/QtWidgetsApplication3/icon/cursor_down.png"
#define GCP_ICON ":/QtWidgetsApplication3/icon/GCPs.png"
#define DELETE_ICON ":/QtWidgetsApplication3/icon/delete.png"

#define NOT_IN_PROCESS "not_in_process"
#define IN_PROCESS "in_process"
